### ISSUE TITLE
Выводится неправильное число друзей пользователей

### ISSUE THREAD

**Issue by disovi** [Anton-Mushnin/vk-vue-ts#1]
![image](https://user-images.githubusercontent.com/705617/196704959-2653ee11-5781-44fd-af7e-944a58daded6.png) а должно быть 198, по всем пользователям цифры произвольные

**Comment by Anton-Mushnin** [comment]
Это не произвольные числа, это значение поля followers_count. Я думал, это и есть друзья

**Comment by disovi** [comment]
@Anton-Mushnin понятно, надо заменить на число друзей

**Comment by Anton-Mushnin** [comment]
Заменил

**Comment by Anton-Mushnin** [comment]
@disovi 
А вы поделитесь со мной впечатлением от моего решения вашего тестового задания?
