### ISSUE TITLE
Список друзей не отсортирован по ФИО

### ISSUE THREAD

**Issue by disovi** [Anton-Mushnin/vk-vue-ts#2]
> Пользователи должны быть отсортированы по фамилии/имени (с отображением пола, возраста, количества друзей и фотографии)

![image](https://user-images.githubusercontent.com/705617/196706899-03261cbd-fb3d-4517-933e-c3902f4c4f23.png)

**Comment by Anton-Mushnin** [comment]
Я был настолько уверен, что сортировать нужно по возрасту, что посмотрел не только ТЗ, но и его историю изменений. )

Исправил.
